class DocumentParser:
    def parse_passport(self, image_bytes: bytes) -> dict:
        ...

    def parse_profile(self, docx_bytes: bytes) -> dict:
        ...

    def parse_form(self, pdf_bytes: bytes) -> dict:
        ...

    def parse_description(self, txt_bytes: bytes) -> dict:
        ...
